---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: redis
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    requirepass demopasswordchangeme123
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: example-redis-config
        items:
        - key: redis-config
          path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis
  ports:
    - name: http
      port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 32767
  type: LoadBalancer

