# # Redis Insight service with name 'redisinsight-service'
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis       # name should not be 'redisinsight'
#                                    # since the service creates
#                                    # environment variables that
#                                    # conflicts with redisinsight
#                                    # application's environment
#                                    # variables `RI_APP_HOST` and
#                                    # `RI_APP_PORT`
#   namespace: redis
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 10111
#       targetPort: 10111
#   selector:
#     app: redis-cluster
# ---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redisdb
  namespace: redis
spec:
  memorySize: 1GB
  redisEnterpriseCluster:
    name: redis-cluster