---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis
  labels:
    app: redis-enterprise
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
  type: LoadBalancer
  selector:
    name: redis-enterprise-operator