apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webapp
  namespace: multiapp
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx-webapp
    nginx.org/client-max-body-size: "4m"
    nginx.org/proxy-buffering: "on"
    nginx.org/proxy-buffer-size: "256k"
    nginx.org/proxy-buffers: "4 512k"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - webapp.multiappauthen.online
    secretName: letsencrypt-nginx-webapp
  rules:
    - host: webapp.multiappauthen.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 8080