apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-echo
  namespace: multiapp
  annotations:
    cert-manager.io/cluster-issuer: "custom-ca-issuer"
    nginx.org/client-max-body-size: "4m"
    nginx.org/proxy-buffering: "on"
    nginx.org/proxy-buffer-size: "256k"
    nginx.org/proxy-buffers: "4 512k"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blazorwebidentity.multiappauthen.online
    secretName: letsencrypt-nginx-private-key-1-identity
  rules:
    - host: blazorwebidentity.multiappauthen.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blazorwebidentity
                port:
                  number: 8080