apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: redis
data:
  redis-config: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    maxmemory 64mb
    maxmemory-policy allkeys-lru
