apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis
  ports:
    - name: http
      port: 6379
      protocol: TCP
      targetPort: 6379
  type: ClusterIP